### ISSUE TITLE
out image file blurred

### ISSUE THREAD

**Issue by journey-ad** [satoshiiizuka/siggraph2016_colorization#13] opened 2016-08-20 14:13 UTC
I running the example command but I got this:(without error)
![out](https://cloud.githubusercontent.com/assets/16256221/17831623/7232e1d2-6720-11e6-8723-29278b822968.png)
I have 8GiB RAM and Ubuntu16.04  CUDA7.5

我按照示例的指令运行后却得到了这样的结果：（没有报错）
![out](https://cloud.githubusercontent.com/assets/16256221/17831623/7232e1d2-6720-11e6-8723-29278b822968.png)
我的内存容量为8GiB，系统是Ubuntu16.04，CUDA版本为7.5

**Comment by journey-ad** [comment] 2016-08-20 14:39
Sometimes i got this:

```
/home/jad/torch/install/bin/luajit: /home/jad/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
/home/jad/torch/install/share/lua/5.1/nn/THNN.lua:109: Wrong number of input channels! Input has 4 channels, expected 1 at /tmp/luarocks_nn-scm-1-1410/nn/lib/THNN/generic/SpatialConvolutionMM.c:99
stack traceback:
	[C]: in function 'v'
	/home/jad/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'SpatialConvolutionMM_updateOutput'
	...ad/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:96: in function <...ad/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:92>
	[C]: in function 'xpcall'
	/home/jad/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/jad/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	/home/jad/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/home/jad/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	colorize.lua:47: in main chunk
	[C]: in function 'dofile'
	.../jad/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/jad/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/jad/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	/home/jad/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/home/jad/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	colorize.lua:47: in main chunk
	[C]: in function 'dofile'
	.../jad/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

```

**Comment by smajida** [comment] 2016-08-22 00:41
Hi, 

@journey-ad  I also have the same problem. the same output image without any errors. Did you figure it out what the problem is?

**Comment by Lyken17** [comment] 2016-11-12 12:15
Two possible reasons.

1. Your 'image' package is outdated, use ```luarocks install image``` to update it.
2. In your log, one line said "Input has 4 channels", i guess it is not standard RGB image. Convert it and then test.

**Comment by bobbens** [comment] 2016-11-21 04:09
Your have an issue with your torch installation. Follow the advice given by @Lyken17 and/or check the official torch documentation. Closing.

**Closed by bobbens** 2016-11-21 04:09 UTC
